version: '3'
services:
  django_app:
    build:
      context: ./django_app
    ports:
      - "8000:8000"
    volumes:
      - ./django_app:/app

  nextjs_app:
    build:
      context: ./nextjs_app
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs_app:/app
