# Generated by Django 4.2.5 on 2023-11-03 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
