# Generated by Django 4.2.5 on 2023-11-25 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order_orderproduct_order_product_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytxn',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 16, 22, 45, 316235, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fruit', 'fruit'), ('vegetable', 'vegetable')], max_length=50),
        ),
    ]
