# Generated by Django 4.2.5 on 2023-11-29 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_inventorytxn_date_alter_product_category'),
        ('app', '0009_order_discount_order_gross_amount_and_more'),
    ]

    operations = [
    ]
