# Generated by Django 4.2.5 on 2023-11-29 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_order_total_amount_alter_inventorytxn_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytxn',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 11, 31, 35, 616079, tzinfo=datetime.timezone.utc)),
        ),
    ]
