# Generated by Django 4.2.5 on 2023-11-29 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_inventorytxn_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytxn',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 12, 53, 29, 356718, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
