# Generated by Django 4.2.5 on 2023-11-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_merge_20231129_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytxn',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('customer', 'product')},
        ),
    ]
