# Generated by Django 4.2.5 on 2023-11-29 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_inventorytxn_date_alter_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytxn',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 13, 22, 10, 154907, tzinfo=datetime.timezone.utc)),
        ),
    ]
