# Generated by Django 4.2.5 on 2023-11-30 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_inventorytxn_date_alter_cart_unique_together'),
        ('app', '0013_alter_inventorytxn_date'),
    ]

    operations = [
    ]
