# Generated by Django 4.2.5 on 2023-11-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_order_discount_alter_order_gross_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
