# Generated by Django 4.2.5 on 2023-12-01 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_order_discount_remove_order_gross_amount'),
        ('app', '0016_orderproduct_unit_price'),
    ]

    operations = [
    ]
